// GENERATED by edge/netlify-extension/scripts/bundle.mjs — DO NOT EDIT.
// Source: edge/netlify-extension/src/sensor. Rebuild with `npm run build:bundle`.
// src/sensor/agents.generated.ts
var AGENTS = [
  ["reflectionbot", "Reflectionbot", "reflectionbot", "crawler"],
  ["gptbot", "GPTBot", "gptbot", "crawler"],
  ["chatgpt-user", "ChatGPT-User", "chatgpt-user", "crawler"],
  ["chatgpt", "ChatGPT-User", "chatgpt-user", "crawler"],
  ["oai-searchbot", "OAI-SearchBot", "oai-searchbot", "crawler"],
  ["claudebot", "ClaudeBot", "claudebot", "crawler"],
  ["anthropic", "Anthropic", "anthropic", "crawler"],
  ["ccbot", "CCBot", "ccbot", "crawler"],
  ["google-extended", "Google-Extended", "google-extended", "crawler"],
  ["bytespider", "ByteSpider", "bytespider", "crawler"],
  ["amazonbot", "Amazonbot", "amazonbot", "crawler"],
  ["facebookbot", "FacebookBot", "facebookbot", "crawler"],
  ["meta-externalagent", "Meta-ExternalAgent", "meta-externalagent", "crawler"],
  ["cohere-ai", "Cohere", "cohere-ai", "crawler"],
  ["cohere", "Cohere", "cohere-ai", "crawler"],
  ["perplexitybot", "PerplexityBot", "perplexitybot", "crawler"],
  ["applebot-extended", "Applebot-Extended", "applebot-extended", "crawler"],
  ["youbot", "YouBot", "youbot", "crawler"],
  ["mistral", "MistralBot", "mistral", "crawler"],
  ["gemini", "Gemini", "gemini", "crawler"],
  ["ai2bot", "AI2Bot", "ai2bot", "crawler"],
  ["deepseek", "DeepSeek", "deepseek", "crawler"],
  ["qwen", "Qwen", "qwen", "crawler"],
  ["webzio", "Webz.io", "webzio", "crawler"],
  ["sentibot", "Sentibot", "sentibot", "crawler"],
  ["omgili", "Omgili", "omgili", "crawler"],
  ["img2dataset", "img2dataset", "img2dataset", "crawler"],
  ["timpibot", "Timpibot", "timpibot", "crawler"],
  ["velenpublicwebcrawler", "VelenPublicWebCrawler", "velenpublicwebcrawler", "crawler"],
  ["isscyberriskcrawler", "ISSCyberRiskCrawler", "isscyberriskcrawler", "crawler"],
  ["friendlycrawler", "FriendlyCrawler", "friendlycrawler", "crawler"],
  ["duckassistbot", "DuckAssistBot", "duckassistbot", "crawler"],
  ["sofyabot", "SofyaBot", "sofyabot", "crawler"],
  ["xai-searchbot", "xAI-SearchBot", "xai-searchbot", "crawler"],
  ["linkupbot", "LinkupBot", "linkupbot", "crawler"],
  ["searchgpt", "SearchGPT", "searchgpt", "crawler"],
  ["phind", "Phind", "phind", "crawler"],
  ["kagi", "Kagi", "kagi", "crawler"],
  ["exa.ai", "Exa", "exa", "crawler"],
  ["exabot", "Exa", "exa", "crawler"],
  ["metaphor", "Metaphor", "metaphor", "crawler"],
  ["tavily", "Tavily", "tavily", "crawler"],
  ["bravesearch", "BraveSearch", "brave-search", "crawler"],
  ["neevabot", "NeevaBot", "neeva", "crawler"],
  ["operator", "Operator", "operator", "crawler"],
  ["claude-user", "Claude-User", "claude-user", "crawler"],
  ["gemini-user", "Gemini-User", "gemini-user", "crawler"],
  ["googleagent-mariner", "GoogleAgent-Mariner", "googleagent-mariner", "crawler"],
  ["mariner", "GoogleAgent-Mariner", "googleagent-mariner", "crawler"],
  ["amazonbuyforme", "AmazonBuyForMe", "amazon-buyforme", "crawler"],
  ["buyforme", "AmazonBuyForMe", "amazon-buyforme", "crawler"],
  ["browser-use", "Browser-Use", "browser-use", "crawler"],
  ["stagehand", "Stagehand", "stagehand", "crawler"],
  ["multion", "MultiOn", "multion", "crawler"],
  ["iboubot", "IbouBot", "iboubot", "crawler"],
  ["googlebot", "Googlebot", "googlebot", "crawler"],
  ["bingbot", "Bingbot", "bingbot", "crawler"],
  ["yandexbot", "YandexBot", "yandexbot", "crawler"],
  ["baiduspider", "Baiduspider", "baiduspider", "crawler"],
  ["duckduckbot", "DuckDuckBot", "duckduckbot", "crawler"],
  ["applebot", "Applebot", "applebot", "crawler"],
  ["sogou", "Sogou Spider", "sogou", "crawler"],
  ["qwantify", "Qwantify", "qwantify", "crawler"],
  ["naver", "Naver", "naver", "crawler"],
  ["yeti", "Naver", "naver", "crawler"],
  ["seznambot", "SeznamBot", "seznam", "crawler"],
  ["ecosia", "Ecosia", "ecosia", "crawler"],
  ["mojeekbot", "MojeekBot", "mojeek", "crawler"],
  ["slurp", "Yahoo! Slurp", "yahoo-slurp", "crawler"],
  ["ahrefsbot", "AhrefsBot", "ahrefsbot", "crawler"],
  ["ahrefs", "AhrefsBot", "ahrefsbot", "crawler"],
  ["semrushbot", "SemrushBot", "semrushbot", "crawler"],
  ["semrush", "SemrushBot", "semrushbot", "crawler"],
  ["mj12bot", "MJ12bot", "mj12bot", "crawler"],
  ["dotbot", "DotBot", "dotbot", "crawler"],
  ["rogerbot", "Rogerbot", "rogerbot", "crawler"],
  ["screaming frog", "Screaming Frog", "screaming-frog", "crawler"],
  ["sitebulb", "Sitebulb", "sitebulb", "crawler"],
  ["deepcrawl", "DeepCrawl", "deepcrawl", "crawler"],
  ["oncrawl", "OnCrawl", "oncrawl", "crawler"],
  ["botify", "Botify", "botify", "crawler"],
  ["contentking", "ContentKing", "contentking", "crawler"],
  ["sistrix", "SISTRIX", "sistrix", "crawler"],
  ["serpstat", "Serpstat", "serpstat", "crawler"],
  ["spyfu", "SpyFu", "spyfu", "crawler"],
  ["nessus", "Nessus", "nessus", "crawler"],
  ["qualys", "Qualys", "qualys", "crawler"],
  ["shodan", "Shodan", "shodan", "crawler"],
  ["censys", "Censys", "censys", "crawler"],
  ["nmap", "Nmap", "nmap", "crawler"],
  ["zap/", "OWASP ZAP", "zap", "crawler"],
  ["burp", "Burp Suite", "burp", "crawler"],
  ["nikto", "Nikto", "nikto", "crawler"],
  ["nuclei", "Nuclei", "nuclei", "crawler"],
  ["acunetix", "Acunetix", "acunetix", "crawler"],
  ["netsparker", "Netsparker", "netsparker", "crawler"],
  ["detectify", "Detectify", "detectify", "crawler"],
  ["intruder", "Intruder", "intruder", "crawler"],
  ["python-requests", "Python-Requests", "python-requests", "tool"],
  ["python-urllib", "Python-urllib", "python-urllib", "tool"],
  ["python/", "Python", "python", "tool"],
  ["scrapy", "Scrapy", "scrapy", "tool"],
  ["httpx", "HTTPX", "httpx", "tool"],
  ["aiohttp", "aiohttp", "aiohttp", "tool"],
  ["beautifulsoup", "BeautifulSoup", "beautifulsoup", "tool"],
  ["node-fetch", "node-fetch", "node-fetch", "tool"],
  ["axios/", "Axios", "axios", "tool"],
  ["got/", "Got", "got", "tool"],
  ["undici", "Undici", "undici", "tool"],
  ["go-http-client", "Go-HTTP-Client", "go-http-client", "tool"],
  ["colly", "Colly", "colly", "tool"],
  ["java/", "Java", "java", "tool"],
  ["okhttp", "OkHttp", "okhttp", "tool"],
  ["apache-httpclient", "Apache-HttpClient", "apache-httpclient", "tool"],
  ["jsoup", "Jsoup", "jsoup", "tool"],
  ["guzzlehttp", "GuzzleHttp", "guzzlehttp", "tool"],
  ["php/", "PHP", "php", "tool"],
  ["ruby", "Ruby", "ruby", "tool"],
  ["faraday", "Faraday", "faraday", "tool"],
  ["mechanize", "Mechanize", "mechanize", "tool"],
  ["headlesschrome", "HeadlessChrome", "headlesschrome", "tool"],
  ["puppeteer", "Puppeteer", "puppeteer", "tool"],
  ["playwright", "Playwright", "playwright", "tool"],
  ["selenium", "Selenium", "selenium", "tool"],
  ["phantomjs", "PhantomJS", "phantomjs", "tool"],
  ["splash", "Splash", "splash", "tool"],
  ["browserless", "Browserless", "browserless", "tool"],
  ["browserbase", "Browserbase", "browserbase", "tool"],
  ["ia_archiver", "Internet Archive", "ia-archiver", "crawler"],
  ["archive.org_bot", "Archive.org", "archive-org-bot", "crawler"],
  ["wayback", "Wayback Machine", "wayback", "crawler"],
  ["heritrix", "Heritrix", "heritrix", "crawler"],
  ["brozzler", "Brozzler", "brozzler", "crawler"],
  ["facebookexternalhit", "Facebook", "facebookexternalhit", "crawler"],
  ["twitterbot", "Twitterbot", "twitterbot", "crawler"],
  ["linkedinbot", "LinkedInBot", "linkedinbot", "crawler"],
  ["slackbot", "Slackbot", "slackbot", "crawler"],
  ["telegrambot", "TelegramBot", "telegrambot", "crawler"],
  ["whatsapp", "WhatsApp", "whatsapp", "crawler"],
  ["discordbot", "Discordbot", "discordbot", "crawler"],
  ["pinterest", "Pinterest", "pinterestbot", "crawler"],
  ["tumblr", "Tumblr", "tumblr", "crawler"],
  ["reddit", "Reddit", "reddit", "crawler"],
  ["embedly", "Embedly", "embedly", "crawler"],
  ["iframely", "Iframely", "iframely", "crawler"],
  ["curl/", "cURL", "curl", "tool"],
  ["wget/", "Wget", "wget", "tool"],
  ["libwww-perl", "libwww-perl", "libwww-perl", "tool"],
  ["lwp-", "LWP", "lwp", "tool"],
  ["httrack", "HTTrack", "httrack", "tool"],
  ["webdecoybot", "WebDecoyBot", "webdecoybot", "crawler"],
  ["uptimerobot", "UptimeRobot", "uptimerobot", "crawler"],
  ["pingdom", "Pingdom", "pingdom", "crawler"],
  ["statuscake", "StatusCake", "statuscake", "crawler"],
  ["betteruptime", "Better Uptime", "better-uptime", "crawler"],
  ["datadog", "Datadog Synthetics", "datadog-synthetics", "crawler"],
  ["newrelic", "New Relic", "newrelic", "crawler"],
  ["site24x7", "Site24x7", "site24x7", "crawler"],
  ["freshping", "Freshping", "freshping", "crawler"],
  ["hetrixtools", "HetrixTools", "hetrixtools", "crawler"],
  ["nodeping", "NodePing", "nodeping", "crawler"],
  ["feedly", "Feedly", "feedly", "crawler"],
  ["newsblur", "NewsBlur", "newsblur", "crawler"],
  ["inoreader", "Inoreader", "inoreader", "crawler"],
  ["theoldreader", "The Old Reader", "theoldreader", "crawler"],
  ["feedbin", "Feedbin", "feedbin", "crawler"],
  ["miniflux", "Miniflux", "miniflux", "crawler"],
  ["freshrss", "FreshRSS", "freshrss", "crawler"],
  ["commafeed", "CommaFeed", "commafeed", "crawler"],
  ["diffbot", "Diffbot", "diffbot", "crawler"],
  ["import.io", "Import.io", "import-io", "crawler"],
  ["brightdata", "Bright Data", "bright-data", "crawler"],
  ["luminati", "Bright Data", "bright-data", "crawler"],
  ["oxylabs", "Oxylabs", "oxylabs", "crawler"],
  ["scrapingbee", "ScrapingBee", "scrapingbee", "crawler"],
  ["scrapingant", "ScrapingAnt", "scrapingant", "crawler"],
  ["zyte", "Zyte", "zyte", "crawler"],
  ["scrapinghub", "Zyte", "zyte", "crawler"],
  ["apify", "Apify", "apify", "crawler"],
  ["crawlbase", "Crawlbase", "crawlbase", "crawler"],
  ["webscrapingapi", "WebScrapingAPI", "webscrapingapi", "crawler"],
  ["gemini-deep-research", "Gemini-Deep-Research", "gemini-deep-research", "crawler"],
  ["copilot", "Microsoft Copilot", "copilot", "crawler"],
  ["cortana", "Cortana", "cortana", "crawler"],
  ["siri", "Siri", "siri", "crawler"]
];

// src/sensor/classify.ts
function matchAgent(ua) {
  for (const [token, name, id, kind] of AGENTS) {
    if (ua.includes(token)) return { name, id, kind };
  }
  return null;
}
var GENERIC_BOT = /(?:bot|crawler|spider)(?:[/\s);,]|$)/i;
var CRAWLER_PATHS = /^\/(?:robots\.txt|sitemap[\w.-]*\.xml|sitemaps?\/)/i;
var CLAIMS_CHROMIUM = /(?:chrome|chromium|edg)\//i;
var IOS_WRAPPER = /(?:crios|edgios|fxios)\//i;
function classify(request, url) {
  const flags = [];
  const h = request.headers;
  const rawUA = h.get("user-agent") ?? "";
  const ua = rawUA.toLowerCase();
  if (ua.trimStart().startsWith("webdecoy-test/")) {
    flags.push("test_trigger");
  }
  if (h.get("signature-agent") || h.get("signature-input")) {
    flags.push("wba_signature");
  }
  const agent = matchAgent(ua);
  const ai = agent?.name ?? "";
  if (agent?.kind === "crawler" || !agent && GENERIC_BOT.test(rawUA)) {
    flags.push("known_crawler_ua");
  }
  if (agent?.kind === "tool") {
    flags.push("http_client_ua");
  }
  if (CRAWLER_PATHS.test(url.pathname)) {
    flags.push("crawler_path");
  }
  if (url.protocol === "https:" && CLAIMS_CHROMIUM.test(ua) && !IOS_WRAPPER.test(ua) && !h.get("sec-ch-ua")) {
    flags.push("missing_client_hints");
  }
  if (!rawUA) {
    flags.push("no_user_agent");
  }
  if (!h.get("accept-language")) {
    flags.push("no_language");
  }
  if (!h.get("sec-fetch-mode")) {
    flags.push("no_fetch_metadata");
  }
  return { send: flags.length > 0, flags, ai };
}
var STATIC_ASSET = /\.(?:js|mjs|css|map|png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|otf|eot|mp4|webm|mp3|pdf|txt|json|xml)$/i;
var STATIC_PREFIX = /^\/(?:_next\/static\/|_astro\/|assets\/|static\/|\.netlify\/)/;
function isStaticAsset(pathname) {
  if (CRAWLER_PATHS.test(pathname)) return false;
  return STATIC_ASSET.test(pathname) || STATIC_PREFIX.test(pathname);
}

// src/sensor/payload.ts
var SOURCE = "netlify_edge";
var EDGE_INJECTED = /^(?:x-nf-|x-forwarded-|x-country|x-language|x-bb-|via$|forwarded$)/;
function clientSignals(request) {
  const h = request.headers;
  const names = [];
  for (const [name] of h) {
    const n = name.toLowerCase();
    if (!EDGE_INJECTED.test(n)) names.push(n);
  }
  names.sort();
  return {
    hn: names,
    al: h.get("accept-language") ?? "",
    ae: h.get("accept-encoding") ?? "",
    ja3: "",
    ja4: "",
    tls: "",
    tc: ""
  };
}
function buildPayload(request, url, siteKey, scannerId, context, v) {
  const h = request.headers;
  return {
    aid: siteKey,
    sid: scannerId,
    v: 2,
    s: 0,
    f: v.flags,
    ai: v.ai,
    source: SOURCE,
    ua: h.get("user-agent") ?? "",
    ip: context.ip ?? "",
    url: url.toString(),
    ref: h.get("referer") ?? "",
    ts: Date.now(),
    cs: clientSignals(request),
    metadata: {
      edge: "netlify",
      method: request.method,
      country: context.geo?.country?.code ?? null,
      netlify_site: context.site?.id ?? "",
      netlify_request_id: context.requestId ?? ""
    }
  };
}

// src/sensor/entry.ts
var DEFAULT_INGEST = "https://in.webdecoy.com";
var BEACON_TIMEOUT_MS = 2e3;
function readEnv(get) {
  const siteKey = (get("WEBDECOY_SITE_KEY") ?? "").trim();
  const scannerId = (get("WEBDECOY_SCANNER_ID") ?? "").trim();
  const sensorKey = (get("WEBDECOY_SENSOR_KEY") ?? "").trim();
  if (!siteKey || !scannerId || !sensorKey) return null;
  const ingest = (get("WEBDECOY_INGEST") ?? "").trim().replace(/\/+$/, "") || DEFAULT_INGEST;
  return { siteKey, scannerId, sensorKey, ingest };
}
async function sendBeacon(env, payload, fetcher = fetch) {
  try {
    await fetcher(`${env.ingest}/api/v1/detect/public`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-wd-sensor-key": env.sensorKey },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(BEACON_TIMEOUT_MS)
    });
  } catch {
  }
}
function makeHandler(getEnv, fetcher = fetch) {
  return (request, context) => {
    try {
      const env = readEnv(getEnv);
      if (!env) return void 0;
      const url = new URL(request.url);
      if (isStaticAsset(url.pathname)) return void 0;
      const verdict = classify(request, url);
      if (!verdict.send) return void 0;
      const payload = buildPayload(request, url, env.siteKey, env.scannerId, context, verdict);
      const beacon = sendBeacon(env, payload, fetcher);
      if (typeof context.waitUntil === "function") {
        context.waitUntil(beacon);
      }
    } catch {
    }
    return void 0;
  };
}
var handler = makeHandler(
  (name) => typeof Netlify !== "undefined" ? Netlify.env.get(name) : void 0
);
var entry_default = handler;
var config = {
  path: "/*",
  // Assets are skipped in code too; excluding them here saves the invocation.
  excludedPath: ["/*.css", "/*.js", "/*.mjs", "/*.map", "/*.png", "/*.jpg", "/*.jpeg", "/*.gif", "/*.webp", "/*.avif", "/*.svg", "/*.ico", "/*.woff", "/*.woff2", "/_next/static/*", "/_astro/*", "/.netlify/*"],
  // If the function itself throws, serve the request as if it were not there.
  onError: "bypass"
};
export {
  config,
  entry_default as default,
  makeHandler,
  readEnv,
  sendBeacon
};
