/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: pkg/agents in the WebDecoy/app repository. Regenerate with
 *   npm run gen:agents
 * in edge/clearance-worker (it runs `go run ./cmd/export-agent-registry -worker`).
 *
 * ORDER IS SIGNIFICANT. Rows are in agents.MatchUserAgent order and the
 * sensor takes the first row whose pattern the lower-cased User-Agent
 * contains. Sorting this reclassifies real traffic: "applebot-extended" must
 * be found before "applebot".
 */

/** What the sensor reports a match as: a self-named crawler, or an HTTP client / automation tool. */
export type AgentKind = 'crawler' | 'tool';

/** [lower-cased UA substring, display name, registry id, kind], in match order. */
export const AGENTS: ReadonlyArray<readonly [string, string, string, AgentKind]> = [
  ['reflectionbot', 'Reflectionbot', 'reflectionbot', 'crawler'],
  ['gptbot', 'GPTBot', 'gptbot', 'crawler'],
  ['chatgpt-user', 'ChatGPT-User', 'chatgpt-user', 'crawler'],
  ['chatgpt', 'ChatGPT-User', 'chatgpt-user', 'crawler'],
  ['oai-searchbot', 'OAI-SearchBot', 'oai-searchbot', 'crawler'],
  ['claudebot', 'ClaudeBot', 'claudebot', 'crawler'],
  ['anthropic', 'Anthropic', 'anthropic', 'crawler'],
  ['ccbot', 'CCBot', 'ccbot', 'crawler'],
  ['google-extended', 'Google-Extended', 'google-extended', 'crawler'],
  ['bytespider', 'ByteSpider', 'bytespider', 'crawler'],
  ['amazonbot', 'Amazonbot', 'amazonbot', 'crawler'],
  ['facebookbot', 'FacebookBot', 'facebookbot', 'crawler'],
  ['meta-externalagent', 'Meta-ExternalAgent', 'meta-externalagent', 'crawler'],
  ['cohere-ai', 'Cohere', 'cohere-ai', 'crawler'],
  ['cohere', 'Cohere', 'cohere-ai', 'crawler'],
  ['perplexitybot', 'PerplexityBot', 'perplexitybot', 'crawler'],
  ['applebot-extended', 'Applebot-Extended', 'applebot-extended', 'crawler'],
  ['youbot', 'YouBot', 'youbot', 'crawler'],
  ['mistral', 'MistralBot', 'mistral', 'crawler'],
  ['gemini', 'Gemini', 'gemini', 'crawler'],
  ['ai2bot', 'AI2Bot', 'ai2bot', 'crawler'],
  ['deepseek', 'DeepSeek', 'deepseek', 'crawler'],
  ['qwen', 'Qwen', 'qwen', 'crawler'],
  ['webzio', 'Webz.io', 'webzio', 'crawler'],
  ['sentibot', 'Sentibot', 'sentibot', 'crawler'],
  ['omgili', 'Omgili', 'omgili', 'crawler'],
  ['img2dataset', 'img2dataset', 'img2dataset', 'crawler'],
  ['timpibot', 'Timpibot', 'timpibot', 'crawler'],
  ['velenpublicwebcrawler', 'VelenPublicWebCrawler', 'velenpublicwebcrawler', 'crawler'],
  ['isscyberriskcrawler', 'ISSCyberRiskCrawler', 'isscyberriskcrawler', 'crawler'],
  ['friendlycrawler', 'FriendlyCrawler', 'friendlycrawler', 'crawler'],
  ['duckassistbot', 'DuckAssistBot', 'duckassistbot', 'crawler'],
  ['sofyabot', 'SofyaBot', 'sofyabot', 'crawler'],
  ['xai-searchbot', 'xAI-SearchBot', 'xai-searchbot', 'crawler'],
  ['linkupbot', 'LinkupBot', 'linkupbot', 'crawler'],
  ['searchgpt', 'SearchGPT', 'searchgpt', 'crawler'],
  ['phind', 'Phind', 'phind', 'crawler'],
  ['kagi', 'Kagi', 'kagi', 'crawler'],
  ['exa.ai', 'Exa', 'exa', 'crawler'],
  ['exabot', 'Exa', 'exa', 'crawler'],
  ['metaphor', 'Metaphor', 'metaphor', 'crawler'],
  ['tavily', 'Tavily', 'tavily', 'crawler'],
  ['bravesearch', 'BraveSearch', 'brave-search', 'crawler'],
  ['neevabot', 'NeevaBot', 'neeva', 'crawler'],
  ['operator', 'Operator', 'operator', 'crawler'],
  ['claude-user', 'Claude-User', 'claude-user', 'crawler'],
  ['gemini-user', 'Gemini-User', 'gemini-user', 'crawler'],
  ['googleagent-mariner', 'GoogleAgent-Mariner', 'googleagent-mariner', 'crawler'],
  ['mariner', 'GoogleAgent-Mariner', 'googleagent-mariner', 'crawler'],
  ['amazonbuyforme', 'AmazonBuyForMe', 'amazon-buyforme', 'crawler'],
  ['buyforme', 'AmazonBuyForMe', 'amazon-buyforme', 'crawler'],
  ['browser-use', 'Browser-Use', 'browser-use', 'crawler'],
  ['stagehand', 'Stagehand', 'stagehand', 'crawler'],
  ['multion', 'MultiOn', 'multion', 'crawler'],
  ['iboubot', 'IbouBot', 'iboubot', 'crawler'],
  ['googlebot', 'Googlebot', 'googlebot', 'crawler'],
  ['bingbot', 'Bingbot', 'bingbot', 'crawler'],
  ['yandexbot', 'YandexBot', 'yandexbot', 'crawler'],
  ['baiduspider', 'Baiduspider', 'baiduspider', 'crawler'],
  ['duckduckbot', 'DuckDuckBot', 'duckduckbot', 'crawler'],
  ['applebot', 'Applebot', 'applebot', 'crawler'],
  ['sogou', 'Sogou Spider', 'sogou', 'crawler'],
  ['qwantify', 'Qwantify', 'qwantify', 'crawler'],
  ['naver', 'Naver', 'naver', 'crawler'],
  ['yeti', 'Naver', 'naver', 'crawler'],
  ['seznambot', 'SeznamBot', 'seznam', 'crawler'],
  ['ecosia', 'Ecosia', 'ecosia', 'crawler'],
  ['mojeekbot', 'MojeekBot', 'mojeek', 'crawler'],
  ['slurp', 'Yahoo! Slurp', 'yahoo-slurp', 'crawler'],
  ['ahrefsbot', 'AhrefsBot', 'ahrefsbot', 'crawler'],
  ['ahrefs', 'AhrefsBot', 'ahrefsbot', 'crawler'],
  ['semrushbot', 'SemrushBot', 'semrushbot', 'crawler'],
  ['semrush', 'SemrushBot', 'semrushbot', 'crawler'],
  ['mj12bot', 'MJ12bot', 'mj12bot', 'crawler'],
  ['dotbot', 'DotBot', 'dotbot', 'crawler'],
  ['rogerbot', 'Rogerbot', 'rogerbot', 'crawler'],
  ['screaming frog', 'Screaming Frog', 'screaming-frog', 'crawler'],
  ['sitebulb', 'Sitebulb', 'sitebulb', 'crawler'],
  ['deepcrawl', 'DeepCrawl', 'deepcrawl', 'crawler'],
  ['oncrawl', 'OnCrawl', 'oncrawl', 'crawler'],
  ['botify', 'Botify', 'botify', 'crawler'],
  ['contentking', 'ContentKing', 'contentking', 'crawler'],
  ['sistrix', 'SISTRIX', 'sistrix', 'crawler'],
  ['serpstat', 'Serpstat', 'serpstat', 'crawler'],
  ['spyfu', 'SpyFu', 'spyfu', 'crawler'],
  ['nessus', 'Nessus', 'nessus', 'crawler'],
  ['qualys', 'Qualys', 'qualys', 'crawler'],
  ['shodan', 'Shodan', 'shodan', 'crawler'],
  ['censys', 'Censys', 'censys', 'crawler'],
  ['nmap', 'Nmap', 'nmap', 'crawler'],
  ['zap/', 'OWASP ZAP', 'zap', 'crawler'],
  ['burp', 'Burp Suite', 'burp', 'crawler'],
  ['nikto', 'Nikto', 'nikto', 'crawler'],
  ['nuclei', 'Nuclei', 'nuclei', 'crawler'],
  ['acunetix', 'Acunetix', 'acunetix', 'crawler'],
  ['netsparker', 'Netsparker', 'netsparker', 'crawler'],
  ['detectify', 'Detectify', 'detectify', 'crawler'],
  ['intruder', 'Intruder', 'intruder', 'crawler'],
  ['python-requests', 'Python-Requests', 'python-requests', 'tool'],
  ['python-urllib', 'Python-urllib', 'python-urllib', 'tool'],
  ['python/', 'Python', 'python', 'tool'],
  ['scrapy', 'Scrapy', 'scrapy', 'tool'],
  ['httpx', 'HTTPX', 'httpx', 'tool'],
  ['aiohttp', 'aiohttp', 'aiohttp', 'tool'],
  ['beautifulsoup', 'BeautifulSoup', 'beautifulsoup', 'tool'],
  ['node-fetch', 'node-fetch', 'node-fetch', 'tool'],
  ['axios/', 'Axios', 'axios', 'tool'],
  ['got/', 'Got', 'got', 'tool'],
  ['undici', 'Undici', 'undici', 'tool'],
  ['go-http-client', 'Go-HTTP-Client', 'go-http-client', 'tool'],
  ['colly', 'Colly', 'colly', 'tool'],
  ['java/', 'Java', 'java', 'tool'],
  ['okhttp', 'OkHttp', 'okhttp', 'tool'],
  ['apache-httpclient', 'Apache-HttpClient', 'apache-httpclient', 'tool'],
  ['jsoup', 'Jsoup', 'jsoup', 'tool'],
  ['guzzlehttp', 'GuzzleHttp', 'guzzlehttp', 'tool'],
  ['php/', 'PHP', 'php', 'tool'],
  ['ruby', 'Ruby', 'ruby', 'tool'],
  ['faraday', 'Faraday', 'faraday', 'tool'],
  ['mechanize', 'Mechanize', 'mechanize', 'tool'],
  ['headlesschrome', 'HeadlessChrome', 'headlesschrome', 'tool'],
  ['puppeteer', 'Puppeteer', 'puppeteer', 'tool'],
  ['playwright', 'Playwright', 'playwright', 'tool'],
  ['selenium', 'Selenium', 'selenium', 'tool'],
  ['phantomjs', 'PhantomJS', 'phantomjs', 'tool'],
  ['splash', 'Splash', 'splash', 'tool'],
  ['browserless', 'Browserless', 'browserless', 'tool'],
  ['browserbase', 'Browserbase', 'browserbase', 'tool'],
  ['ia_archiver', 'Internet Archive', 'ia-archiver', 'crawler'],
  ['archive.org_bot', 'Archive.org', 'archive-org-bot', 'crawler'],
  ['wayback', 'Wayback Machine', 'wayback', 'crawler'],
  ['heritrix', 'Heritrix', 'heritrix', 'crawler'],
  ['brozzler', 'Brozzler', 'brozzler', 'crawler'],
  ['facebookexternalhit', 'Facebook', 'facebookexternalhit', 'crawler'],
  ['twitterbot', 'Twitterbot', 'twitterbot', 'crawler'],
  ['linkedinbot', 'LinkedInBot', 'linkedinbot', 'crawler'],
  ['slackbot', 'Slackbot', 'slackbot', 'crawler'],
  ['telegrambot', 'TelegramBot', 'telegrambot', 'crawler'],
  ['whatsapp', 'WhatsApp', 'whatsapp', 'crawler'],
  ['discordbot', 'Discordbot', 'discordbot', 'crawler'],
  ['pinterest', 'Pinterest', 'pinterestbot', 'crawler'],
  ['tumblr', 'Tumblr', 'tumblr', 'crawler'],
  ['reddit', 'Reddit', 'reddit', 'crawler'],
  ['embedly', 'Embedly', 'embedly', 'crawler'],
  ['iframely', 'Iframely', 'iframely', 'crawler'],
  ['curl/', 'cURL', 'curl', 'tool'],
  ['wget/', 'Wget', 'wget', 'tool'],
  ['libwww-perl', 'libwww-perl', 'libwww-perl', 'tool'],
  ['lwp-', 'LWP', 'lwp', 'tool'],
  ['httrack', 'HTTrack', 'httrack', 'tool'],
  ['webdecoybot', 'WebDecoyBot', 'webdecoybot', 'crawler'],
  ['uptimerobot', 'UptimeRobot', 'uptimerobot', 'crawler'],
  ['pingdom', 'Pingdom', 'pingdom', 'crawler'],
  ['statuscake', 'StatusCake', 'statuscake', 'crawler'],
  ['betteruptime', 'Better Uptime', 'better-uptime', 'crawler'],
  ['datadog', 'Datadog Synthetics', 'datadog-synthetics', 'crawler'],
  ['newrelic', 'New Relic', 'newrelic', 'crawler'],
  ['site24x7', 'Site24x7', 'site24x7', 'crawler'],
  ['freshping', 'Freshping', 'freshping', 'crawler'],
  ['hetrixtools', 'HetrixTools', 'hetrixtools', 'crawler'],
  ['nodeping', 'NodePing', 'nodeping', 'crawler'],
  ['feedly', 'Feedly', 'feedly', 'crawler'],
  ['newsblur', 'NewsBlur', 'newsblur', 'crawler'],
  ['inoreader', 'Inoreader', 'inoreader', 'crawler'],
  ['theoldreader', 'The Old Reader', 'theoldreader', 'crawler'],
  ['feedbin', 'Feedbin', 'feedbin', 'crawler'],
  ['miniflux', 'Miniflux', 'miniflux', 'crawler'],
  ['freshrss', 'FreshRSS', 'freshrss', 'crawler'],
  ['commafeed', 'CommaFeed', 'commafeed', 'crawler'],
  ['diffbot', 'Diffbot', 'diffbot', 'crawler'],
  ['import.io', 'Import.io', 'import-io', 'crawler'],
  ['brightdata', 'Bright Data', 'bright-data', 'crawler'],
  ['luminati', 'Bright Data', 'bright-data', 'crawler'],
  ['oxylabs', 'Oxylabs', 'oxylabs', 'crawler'],
  ['scrapingbee', 'ScrapingBee', 'scrapingbee', 'crawler'],
  ['scrapingant', 'ScrapingAnt', 'scrapingant', 'crawler'],
  ['zyte', 'Zyte', 'zyte', 'crawler'],
  ['scrapinghub', 'Zyte', 'zyte', 'crawler'],
  ['apify', 'Apify', 'apify', 'crawler'],
  ['crawlbase', 'Crawlbase', 'crawlbase', 'crawler'],
  ['webscrapingapi', 'WebScrapingAPI', 'webscrapingapi', 'crawler'],
  ['gemini-deep-research', 'Gemini-Deep-Research', 'gemini-deep-research', 'crawler'],
  ['copilot', 'Microsoft Copilot', 'copilot', 'crawler'],
  ['cortana', 'Cortana', 'cortana', 'crawler'],
  ['siri', 'Siri', 'siri', 'crawler'],
];
